services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_db
    ports:
      - "5432:5432"
    env_file:
      - ../config/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_network
    restart: always

  url_shortener:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: url_shortener
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=url_db
      - TEST_ENV=
      - CONFIG_PATH=/app/config/local.yaml
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge