storage: "inmemory" # "inmemory" or "postgres"
db:
  name: "url_db"
  user: "alinasad"
  password: ""
  host: "localhost"
  port: "5432"
http_server:
  address: ":8080"
  timeout: 5s
  idle_timeout: 20s