storage: "postgres" # "inmemory" or "postgres"

http_server:
  address: ":8080"
  timeout: 5s
  idle_timeout: 60s

postgres:
  host: "localhost"
  port: 5431
  user: "alinasad"
  password: ""
  name: "urlshortener"
  max_conn: 10